title: id.Ancient-Hebrew
author:
  name: id.Ancient-Hebrew
  email: admin@ancient-hebrew.org
  email2: andy-saktia@ancient-hebrew.org
  email3: ibrani.kuno@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
# Situs ini merupakan situs resmi dari <a href="https://ancient-hebrew.org" target="_blank">Ancient Hebrew Research Center</a> milik Jeff A. Benner.  

url: http://id.ancient-hebrew.org
#url: http://127.0.0.1:4000

show_excerpts: false # set to true to show excerpts on the homepage
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    #github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
